#!/usr/bin/env bash

DMENU="$HOME/.config/scripts/lib/dmenu.sh"
LINE="$(cat ~/.config/dmenu/qemulist | $DMENU -i -l 8 -p "VM: ")"

CMD="$(printf "%s" "$LINE" | sed -E 's/(.+)?#.*/\1/')"

eval exec $CMD &> /dev/null &!

exit 0
