#!/usr/bin/env bash

DMENU="$HOME/.config/scripts/lib/dmenu.sh"
SESSION="$(tmux list-sessions | sed -rn 's/([^:]+).*/\1/p' | $DMENU -i -l 8 -p "TMUX: ")"

if [[ ! -z $SESSION ]]
then
    alacritty -e tmux -2 attach-session -t $SESSION
fi
