#!/usr/bin/env sh

server=/home/jose/Apps/precompile/jdt-langserver

java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -noverify \
    -Xms1G \
    -jar $server/plugins/org.eclipse.equinox.launcher_1.*.jar \
    -configuration $server/config_linux/ \
    "$@"
